### PR TITLE
Remove unused flag

### PR DESCRIPTION
**Pull request by nrb**
Quick followup to #1906

Signed-off-by: Nolan Brubaker <brubakern@vmware.com>

### CODE REVIEW

**Comment by prydonius** [comment]
Wasn't this flag being used by `generate-groups.sh`: https://github.com/vmware-tanzu/velero/blob/aa9ca9a69d4367ea7604b49118c2143f519dde86/hack/update-generated-crd-code.sh#L42?

**Comment by nrb** [comment]
Ahh, was it? That makes sense, I didn't see that the full args were passed on there.

**Comment by prydonius** [comment]
I believe it's being used there, I didn't add the flag as part of #1885, I just used it to skip the CRD generation (https://github.com/vmware-tanzu/velero/pull/1885/files#diff-892d90adfc5482f1fee4517a4ad27aeeR44). I'll verify that it's being used be `generate-groups.sh`, and if so, we can revert this.

**Comment by skriss** [comment]
Oops, missed that in review too

**Comment by prydonius** [comment]
Can confirm that the `--verify-only` flag is needed here.

After making an API change (e.g. changing BackupStatus CompletionTimestamp field to be a `*metav1.Time` type), running `make verify` does not fail and `pkg/apis/velero/v1/zz_generated.deepcopy.go` gets modified. With the `--verify-only` flag added back, `make verify` fails as expected and `pkg/apis/velero/v1/zz_generated.deepcopy.go` is unchanged:

```
Running all verification scripts
Verifying gofmt
Verifying gofmt - done!
Verifying goimports
Verifying goimports - done!
+ [[ -z /go ]]
+ [[ ! -d /go/src/k8s.io/code-generator ]]
+ [[ ! -d /go/src/sigs.k8s.io/controller-tools ]]
+ /go/src/k8s.io/code-generator/generate-groups.sh all github.com/vmware-tanzu/velero/pkg/generated github.com/vmware-tanzu/velero/pkg/apis velero:v1 --go-header-file /go/src/github.com/vmware-tanzu/velero/hack/boilerplate.go.txt --verify-only
Generating deepcopy funcs
F1004 23:15:43.305762    3876 main.go:82] Error: Failed executing generator: some packages had errors:
errors in package "github.com/vmware-tanzu/velero/pkg/apis/velero/v1":
output for "v1/zz_generated.deepcopy.go" differs; first existing/expected diff:
  "n.CompletionTimestamp.DeepCopyInto(&out.CompletionTimestamp)\n\treturn\n}\n\n// DeepCopy is an autogenera"
  "f in.CompletionTimestamp != nil {\n\t\tin, out := &in.CompletionTimestamp, &out.CompletionTimestamp\n\t\t*"

make[1]: *** [shell] Error 255
make: *** [verify] Error 2
```

I'll open a PR to revert this change.

**Pull request merged**
