### PR TITLE
[DOC] Restic support on OpenShift

### PR DESCRIPTION
**Pull request by abessifi**
On OpenShift, the restic containers should be running in a `privileged` mode to be able to mount the correct hostpath to pods volumes.

### CODE REVIEW

**Comment by abessifi** [comment]
This PR is related to https://github.com/heptio/velero/issues/267 and https://github.com/heptio/velero/issues/406 issues.

**Comment by carlisia** [comment]
@abessifi in the mean time, please amend your commit with a [sign-on](https://github.com/heptio/velero/blob/master/CONTRIBUTING.md).

**Comment by abessifi** [comment]
@carlisia it should be ok now !

**Comment by abessifi** [comment]
@carlisia any update on this ?

**Comment by skriss** [comment]
Hey @abessifi, unfortunately we'll need to you rebase this PR as we've moved docs around in the past few days. You'll now find them under `site/docs` - you'll want to make this change to both `site/docs/master/restic.md` and `site/docs/v1.0.0/restic.md`.

**Comment by skriss** [comment]
Looks like you'll need one more rebase here. I think the conflicting changes were largely just whitespace modifications.

**Comment by abessifi** [comment]
I think this happened because of my Atomic editor. Seems it removes all the leading/extra whitepaces automatically.

**Comment by skriss** [comment]
no worries, looks good now! thanks for the PR :)

**Pull request merged**
