### PR TITLE
Add scaleway support

### PR DESCRIPTION
**Pull request by metal3d**
Add Scaleway.com storage object support (S3 compatible).

### CODE REVIEW

**Comment by skriss** [comment]
@metal3d thanks for coming up with this! 

Our preferred approach to documenting additional S3-compatible providers going forward is for you to publish your own repository with the documentation/sample YAML, and then to submit a PR to `velero` to add a link to it in https://github.com/heptio/velero/blob/master/docs/support-matrix.md#s3-compatible-backup-storage-providers (like the DigitalOcean entry, for example). Does that work for you?

**Comment by metal3d** [comment]
Well no problem for me - I will try to make that.

**Comment by skriss** [comment]
@metal3d I'm going to close this PR, but please do submit a new one with a link to your repo in `docs/support-matrix.md` when you're ready!

**Comment by metal3d** [comment]
Hello,
I'm currently very busy but I will try to make that quickly.

Thanks a lot.

**Pull request closed without merging**
