### PR TITLE
fix broken links to latest stable versions of pages

### LINKED ISSUE #1216: Links to version-specific pages in headers of master docs at heptio.github.io/velero/master are broken
**What steps did you take and what happened:**
The latest version in https://heptio.github.io/velero/master/versions.html points to `v0.10.0versions.html` which is not found.

**What did you expect to happen:**
When I click on the link, it takes me to the latest version.

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

I *think* this fixes #1216 but I don't really have a test environment.

cc @carlisia

### CODE REVIEW

**Comment by carlisia** [comment]
I'll test this.

**Comment by carlisia** [comment]
Seems that the formatting issue was a fluke.

To fix the dupped `velero` in the URL, use this line instead:

`{% assign latest_version = site.latest | append: '/' %`

**Comment by skriss** [comment]
How's this?

**Comment by skriss** [comment]
@carlisia looks like this didn't quite work. i'll take another look at it

**Pull request merged**
