### PR TITLE
Add velero_test.go to assures the logic testing of Velero binary

### PR DESCRIPTION
**Pull request by nzoueidi**
Adding testing for Velero binary. I think this could fixe #872 

Signed-off-by: Naeil Ezzoueidi <naeilzoueidi@ubuntu.com>

### CODE REVIEW

**Comment by skriss** [comment]
@carlisia were you thinking that these CLI tests would interact with the *cobra.Command objects? Or that they'd actually exec a velero binary? I think you were saying the former, right?

Would be great if you could provide some feedback here on the direction you were envisioning.

**Comment by carlisia** [comment]
Hey @nzoueidi, apologies for the delay in getting back. I had something a bit different in mind. Looking at this other example: https://github.com/kubernetes/kubernetes/blob/2981fb7a0171798184b4f860b07870de0ff7b234/cmd/kubeadm/app/cmd/completion_test.go#L92

You see that there are table tests exercising a call the a cobra command. We should have the equivalent for each of our CLI cmds.

**Comment by carlisia** [comment]
Hi @nzoueidi please let me know if i can help you modify this change. Thanks.

**Comment by nzoueidi** [comment]
sure, am on it. Will ping you whenever I need a push 😃

**Comment by skriss** [comment]
@nzoueidi are you still interested in working on this PR?

**Pull request closed without merging**
