### PR TITLE
Add gauge metrics for number of existing backups and restores

### LINKED ISSUE #1077: New gauge metrics for number of existing backups and restores
Ref: [thread on google groups](https://groups.google.com/forum/#!topic/heptio-ark/8mECN2CuQ14)

**Describe the solution you'd like**
I'd like to get new metrics from ark:
- [gauge] number of existing backups based on the number of CRDs (f.e. to track how many backups do we have and if they are deleted properly)
- [gauge] number of existing restores based on the number of CRDs (this one I don't have a use case, rather to make it consistent with backup metrics)

Another metric which can be valuable for me (but maybe questionable for you, I can move it to another issue for discussion or 'reject'):
- [gauge] size of all PV snapshots (labeled with a schedule, volumeSnapshotLocation) - to track how much space do I use.

### PR DESCRIPTION
**Pull request by fabito**
Closes #1077 
Signed-off-by: fabito <fuechi@ciandt.com>

### CODE REVIEW

**Comment by skriss** [comment]
So far so good. I'm thinking maybe we call these metrics `backup_count` and `restore_count`? @nrb WDYT about names?

**Comment by nrb** [comment]
I like `backup_count` and `restore_count`, but I'm concerned they don't conform to convention.

Reading https://prometheus.io/docs/practices/naming/, I wonder if `total_backups` or `total_restores` would be better. That gives us the plural form and the unit (backup/restore) in the name.

**Comment by skriss** [comment]
Based on that sounds like we should use `backups_total` / `restores_total` (similar to `http_requests_total`).

**Comment by nrb** [comment]
Good catch. I'm on board with `backup_total` and `restore_total`.

**Comment by fabito** [comment]
I didn't like the names I picked either. I thought about the _count suffix but found it would be more appropriate for counters.

**Comment by nrb** [comment]
For updating these, I think a a go routine for updating the counters or in the resync functions (as proposed [here](https://github.com/heptio/velero/pull/1280#issuecomment-475426198)) would be ideal. This way, they're kept up-to-date without having to worry about changing all locations that a backup/restore could be created or deleted. That's particularly true for restores, since they can be deleted directly from the client side.

**Comment by fabito** [comment]
Sorry but I still can't tell which option is better/cleaner (haven't studied go routines yet). 
If I take the **resync functions** path. I was thinking on setting the resyncFunc in `NewBackupController` function:

```go
c.resyncFunc = c.resync
c.resyncPeriod = syncPeriod
```
And then create the `resync` function to set the gauge value:

```go
func (c *backupController) resync() {
	backups, err := c.lister.List(labels.Everything())
        c.metrics.SetBackupTotal(len(backups));
}
```

And finally do the same for `restore_total`. Does it make sense ?

**Comment by skriss** [comment]
@fabito I think this looks reasonable as-is -- it's nice and simple, no need to manage our own goroutines for metrics updates.

**Comment by skriss** [comment]
@carlisia or @nrb PTAL

**Comment by skriss** [comment]
@fabito if you're interested in continuing to contribute to velero, I'm happy to help find new issues and provide some direction! We've really appreciated your contributions so far. Let me know.

**Comment by fabito** [comment]
Sure @skriss , point me to another issue and I'll do my best.

**Comment by skriss** [comment]
@fabito https://github.com/heptio/velero/issues/1410 is a relatively small UX enhancement that would be nice to get into v1.0. It would be really nice if we could audit all of the CLI commands and check for any similar missing validation.

https://github.com/heptio/velero/issues/1136 is another metrics request that seems reasonable to add.

**Pull request merged**
