### PR TITLE
v1.0 removals

### LINKED ISSUE #1208: v1.0: remove pkg/apis/ark
`pkg/apis/ark` is deprecated as of v0.11, and should be removed entirely as of v1.0 along with any code using it.

- [x] add deprecation notices
- [ ] remove packages

### LINKED ISSUE #1284: Address all relevant 1.0 TODOs in code
We've used various forms of `// TODO`, `// TODO(1.0)` to note small items that should be changed for 1.0. Many of these cover sections of code that provide backwards-compatibility with older versions of Ark.  We should go through all of these and remove all the code that we can for the 1.0 release.

### PR DESCRIPTION
**Pull request by skriss**
@nrb @carlisia this PR makes me so happy

Fixes #1284

### CODE REVIEW

**Comment by carlisia** [comment]
So. Much. 🔴

**Comment by skriss** [comment]
I've rebased this and added one new commit based on our backwards-compatibility plan discussed this morning (xref #1360).  This should now be ready for review.

**Comment by skriss** [comment]
self-reminder: changelog

**Comment by nrb** [comment]
@skriss Still needs change log :)

**Comment by skriss** [comment]
will do

**Comment by skriss** [comment]
added changelog and rebased

**Pull request merged**
