### PR TITLE
azure: restore disk with zone

### LINKED ISSUE #1159: Azure: Disk with Zone are not restored with Zone
**What steps did you take and what happened:**

- Made a backup with volumes
- Deleted the k8s cluster
- Recreated the cluster
- Restored the backup with volumes

Pod with restored volume can not launch because the Disk restored has no Availability Zone 
```
Events:
  Type     Reason              Age   From                     Message
  ----     ------              ----  ----                     -------
  Normal   Scheduled           1m    default-scheduler        Successfully assigned monitoring/prometheus-server-dbb7755f-6szrq to k8s10-euw-sandbox-agentzone3-vmss-000000
  Warning  FailedAttachVolume  1m    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-31870f80-142b-11e9-8d0e-000d3a22e4ac" : Attach volume "restore-f2e4d7e5-83c9-424d-a965-fc87b2f705a9" to instance "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/k8s10-EUW-sandbox-RG/providers/Microsoft.Compute/virtualMachineScaleSets/k8s10-euw-sandbox-agentzone3-vmss/virtualMachines/0" failed with compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Disk /subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/k8s10-EUW-sandbox-RG/providers/Microsoft.Compute/disks/restore-f2e4d7e5-83c9-424d-a965-fc87b2f705a9 cannot be attached to the VM because it is not in zone '3'."
```

Here the describe of the backup:

```
sylvain@ubuntu-1604-dev:~/git/k8s-conf[master]$ $GOPATH/src/github.com/heptio/ark/_output/bin/linux/amd64/ark --kubecontext k8s10-euw-sandbox -n backup describe backup 20190111-0842 --details
Name:         20190111-0842
Namespace:    backup
Labels:       ark.heptio.com/storage-location=default
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-01-11 09:42:06 +0100 CET
Completed:  2019-01-11 09:44:51 +0100 CET

Expiration:  2019-02-10 09:42:06 +0100 CET

Validation errors:  <none>

Persistent Volumes:
  pvc-318505c3-142b-11e9-8d0e-000d3a22e4ac:
    Snapshot ID:        /subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/ark-EUW-sandbox-RG/providers/Microsoft.Compute/snapshots/k8s10-EUW-sandbox-dynamic-pvc-318505c3-142b-9558e68f-7b9d-4f2d-b7c6-ce76b2962813
    Type:               Premium_LRS
    Availability Zone:  westeurope-1
    IOPS:               <N/A>
  pvc-31870f80-142b-11e9-8d0e-000d3a22e4ac:
    Snapshot ID:        /subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/ark-EUW-sandbox-RG/providers/Microsoft.Compute/snapshots/k8s10-EUW-sandbox-dynamic-pvc-31870f80-142b-029ff66d-a5dd-4a76-82d2-e14f080b9eff
    Type:               Premium_LRS
    Availability Zone:  westeurope-3
    IOPS:               <N/A>
```

**Environment:**

- Ark version (use `ark version`):  2ed241b0b7bce2d69ac291c63ebdc42f85a8ace4-dirty
- Kubernetes version (use `kubectl version`): 1.13.1
- Kubernetes installer & version: aks-engine
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): ubuntu 16.04

### PR DESCRIPTION
**Pull request by sylr**
Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>

Closes #1159

### CODE REVIEW

**Comment by skriss** [comment]
thanks @sylr! Any chance you were able to test this on a cluster supporting availability zones?

**Comment by sylr** [comment]
No, I should have created a draft PR. This is not for merge yet unless someone can test it does not break anything/is working.

**Comment by skriss** [comment]
OK, no problem. Let us know if you're able to test it. I can help out eventually, just need to find the time to figure out how to spin up such a cluster..

**Comment by skriss** [comment]
I was able to get an Azure AZ-based cluster up and running. This code does not work as-is -- it needs to be rebased, and also the `Zones` field is existing just `1`, `2`, etc., whereas the `volumeAZ` param passed in is e.g. `westus2-2`.  We'll probably need to parse it ourselves -- I think we can just split on `-`, and if and only if there's a second part, pass it to `Zones`.

**Comment by skriss** [comment]
OK, I did a quick test with modified code that looked like this:

```go
        // TODO add comment
	parts := strings.Split(volumeAZ, "-")
	if len(parts) == 2 {
		disk.Zones = &[]string{parts[1]}
	}
```

And it worked correctly for both AZ clusters/disks, and non-AZ clusters/disks.

@sylr, if you can update this PR, then we can get it merged and in for v1.0!

**Comment by skriss** [comment]
pls also add a changelog file, `changelogs/unreleased/1298-sylr`

**Comment by sylr** [comment]
@skriss I made it so that it alway take the last item in the array.

**Comment by skriss** [comment]
@nrb or @carlisia pls review/merge when ready.

**Pull request merged**
