### PR TITLE
add more documentation about using official releases

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

On a fresh read through our docs I can see why there's confusion - I think these updates should help a lot. 🤞

### CODE REVIEW

**Comment by ncdc** [comment]
Should we mention Ark/`ark` at all, since all the releases currently available are all `ark`?

**Comment by skriss** [comment]
IDK - once we have 0.11 out (next week) I'd rather not, to keep things simpler for current versions.  I'm fine not merging this 'til ~Wednesday to avoid any additional confusion in the interim.

**Comment by ncdc** [comment]
SGTM

**Comment by skriss** [comment]
I'm dropped the word `velero` from just before "command-line client" on the README so it's applicable for both now and future. I think it's fine to merge now.

**Pull request merged**
